### ISSUE TITLE
Error thrown by Worker: "changing log factory"

### ISSUE THREAD

**Issue by autonomousapps** [jeremymailen/kotlinter-gradle#110]
Version 2.0.0, Gradle 5.4.1.

Just got this stacktrace while testing some changes. Not sure what to make of it. Build still passed.

```
> Task :lintKotlinAll
Changing log factory
java.lang.Throwable
        at org.jetbrains.kotlin.com.intellij.openapi.diagnostic.Logger.setFactory(Logger.java:49)
        at com.pinterest.ktlint.core.KtLint.<clinit>(KtLint.kt:80)
        at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable.lint(LintWorkerRunnable.kt:64)
        at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable.lintKt(LintWorkerRunnable.kt:58)
        at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable.access$lintKt(LintWorkerRunnable.kt:17)
        at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable$run$1$lintFunc$1.invoke(LintWorkerRunnable.kt:37)
        at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable$run$1$lintFunc$1.invoke(LintWorkerRunnable.kt:17)
        at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable.run(LintWorkerRunnable.kt:46)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:58)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:51)
        at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:107)
        at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:101)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by jeremymailen** [comment]
That's weird, does it always happen? I haven't seen it.

It comes from here: https://github.com/pinterest/ktlint/blob/master/ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt#L81

Since `KtLint` is an object, I'd assume that `init` block would only run once. It looks like that error is printed to stdout when some tries to set the logger twice.

**Comment by autonomousapps** [comment]
Only happened once. If it does again, I'll update. I've seen weird stuff before with the Worker API that makes me think things aren't quite synchronized correctly.

**Comment by Naitbit** [comment]
I did just experience it after upgrade to 2.3.0
(Gradle 5.6.4)
```
java.lang.Throwable
	at org.jetbrains.kotlin.com.intellij.openapi.diagnostic.Logger.setFactory(Logger.java:49)
	at com.pinterest.ktlint.core.KtLint.<clinit>(KtLint.kt:86)
	at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable.lint(LintWorkerRunnable.kt:64)
	at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable.lintKt(LintWorkerRunnable.kt:58)
	at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable.access$lintKt(LintWorkerRunnable.kt:17)
	at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable$run$1$lintFunc$1.invoke(LintWorkerRunnable.kt:37)
	at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable$run$1$lintFunc$1.invoke(LintWorkerRunnable.kt:17)
	at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable.run(LintWorkerRunnable.kt:46)
	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:56)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:215)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:210)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
```

It did not happen on subsequent runs though.
Makes me wonder if it is related to updating dependency.

**Comment by jeremymailen** [comment]
Ok, that's good to know. Still a bug, but if it happens once on a version update it's not as severe.

**Comment by jeremymailen** [comment]
Closing for now, hopefully we don't run into it ever again in the new design.

**Comment by fluxxion82** [comment]
I'm getting this error consistently. Currently using 3.6.0 but saw seeing it consistently on earlier versions too. My build is still passing so I'm not too concerned about it. I can post this project later so you can check it out and debug it if you're interested.

**Comment by jeremymailen** [comment]
> I'm getting this error consistently. Currently using 3.6.0 but saw seeing it consistently on earlier versions too. My build is still passing so I'm not too concerned about it. I can post this project later so you can check it out and debug it if you're interested.

Yes, please do, thanks! Having a project that can repro the issue will go a long ways towards figuring out how to fix it.

I assume the lint task still runs successfully?
