### ISSUE TITLE
3.0.0 `formatKotlin` crashes on multi-project build

### ISSUE THREAD

**Issue by marshallpierce** [jeremymailen/kotlinter-gradle#156]
Thanks for getting 3.0.0 out so quickly after kotlin 1.4. It works fine on single-project builds for me so far, but one build has about a dozen subprojects, and when I run the `formatKotlin` task, I get some number of this spat out:

```
Failed to execute org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker@a3984d3.
java.lang.IllegalStateException: Some child operations have not yet completed.
        at org.gradle.internal.work.DefaultWorkerLeaseService$DefaultWorkerLease.releaseLock(DefaultWorkerLeaseService.java:403)
        at org.gradle.internal.resources.AbstractTrackedResourceLock.unlock(AbstractTrackedResourceLock.java:58)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService$ReleaseLocks.transform(DefaultResourceLockCoordinationService.java:216)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService$ReleaseLocks.transform(DefaultResourceLockCoordinationService.java:206)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$execute$2(DefaultPlanExecutor.java:199)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:197)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

The number of repetitions of that stack trace is different each time I run it.

The plugin is wired like so:

```
plugins {
    // ...
    id("org.jmailen.kotlinter") version "3.0.0"
}

tasks.check {
    dependsOn("installKotlinterPrePushHook")
}

subprojects {
    // ...

    apply(plugin = "org.jmailen.kotlinter")
}
```

I also have `org.gradle.parallel = true` enabled in `~/.gradle/gradle.properties`.

**Comment by jeremymailen** [comment]
It looks like the `org.gradle.parallel` is causing the issue. Turning that off allows things to work.

I'll need to look into it a bit later, but there are a couple of possibilities: either the incubating gradle work api isn't safe in parallel more yet, or sharing a single workqueue between tasks running in parallel is not safe.

**Comment by jeremymailen** [comment]
Ok, I believe this is fixed now in https://github.com/jeremymailen/kotlinter-gradle/releases/tag/3.0.1
Give it a try and report back.

**Comment by marshallpierce** [comment]
Works great! You're going to make the rest of us OSS maintainers look bad with your turnaround time ;)
