### ISSUE TITLE
Error when running any command provided by kotlinter-gradle

### ISSUE THREAD

**Issue by LukevanTricht** [jeremymailen/kotlinter-gradle#193]
Received the dependabot PR to upgrade kotlinter-gradle from 3.4.0 to 3.4.3, and the CI for that PR is failing with these errors:

```
> Task :app:lintKotlinDebug FAILED
lint worker execution error
java.lang.NoSuchMethodError: kotlin.jvm.internal.FunctionReferenceImpl.<init>(ILjava/lang/Object;Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
	at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerAction$execute$2$lintFunc$1.<init>(LintWorkerAction.kt)
	at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerAction.execute(LintWorkerAction.kt:42)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:67)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
````

I'm running it on Java 1.8, specifically in an Android Kotlin project.

**Comment by mateuszkwiecinski** [comment]
Hey @LukevanTricht, can you share your Gradle version and Kotlin Gradle Plugin version? 
I'd guess you have a kotlin version conflict, and somehow you end up having Kotlin 1.3 in one of your configurations, but Kotlinter now requires 1.4 - https://github.com/jeremymailen/kotlinter-gradle/pull/176/files#diff-c0dfa6bc7a8685217f70a860145fbdf416d449eaff052fa28352c5cec1a98c06R70 (and btw Kotlin 1.5 deprecates 1.3 language version so you'll face this problem with other libaries eventually as well)

I'll link related issues: https://youtrack.jetbrains.com/issue/KT-41142 and https://github.com/gradle/gradle/issues/16345

You can try to upgrade Gradle (IIRC it bundles kotlin 1.4 since 6.8) or enforce using Kotlin 1.4 in all configurations as in a linked issues (you can run `./gradlew :app:dependencies` to find which Kotlin version do you use for each configuration)

**Comment by jeremymailen** [comment]
Thank you @mateuszkwiecinski. Yes from my experience this kind of error signature is a Kotlin version compatibility conflict. You might be running 1.3.x.

**Comment by LukevanTricht** [comment]
Hey @mateuszkwiecinski we're using Gradle `4.1.3` and Kotlin `1.5.0`, as defined in our gradle files.

**Comment by mateuszkwiecinski** [comment]
Yeah, so that's where the incompatibility comes from. You can either update gradle to at least 6.8 or add
```
allprojects {
    configurations.configureEach {
        resolutionStrategy.eachDependency {
            if (requested.group == "org.jetbrains.kotlin" && requested.name.startsWith("kotlin")) {
                useVersion("1.5.0")
            }
        }
    }
}

```
to your root project `build.gradle` which should ensure consistent Kotlin version in your project.
And of course you can do both 😄 I'd personally also recommend to upgrade Java to 11 🤷 

Anyway, there is nothing that can be done on the `kotlinter` plugin side, you'll have to fix your version conflict in your project. Your build failed pointing at kotlinter only because it must be the first library that migrated from deprecated 1.3 language level.

**Comment by LukevanTricht** [comment]
Right, so just a timeline of events, for my own sanity and my team 😅 

1. Somewhere in the Kotlinter 3.4.0..........3.4.3 upgrade, you guys upgraded your Kotlin language level from 1.3 to 1.5
2. Dependabot made the PR
3. CI failed, due to Kotlin 1.5 not supporting Gradle 6.6? <- I can't find any information on this other than what you have said 😅 
4. Our systems yelled at me.

Does that seem about right? Do you have a link for the gradle/kotlin incompatability?

**Comment by mateuszkwiecinski** [comment]
>upgraded your Kotlin language level from 1.3 to 1.5

to 1.4, in the linked previously: https://github.com/jeremymailen/kotlinter-gradle/pull/176/files#diff-c0dfa6bc7a8685217f70a860145fbdf416d449eaff052fa28352c5cec1a98c06R70

>due to Kotlin 1.5 not supporting Gradle 6.6?

I wouldn't put it that way. I'd rather say: ...due to the fact Kotlinter requires at least Kotlin 1.4, but doesn't enforce it. Gradle 6.6 on the other hand adds Kotlin 1.3 dependency to `classpath` configuration. So when you run Kotlinter task on a Gradle enforced Kotlin version it fails due to incompatibility. It's not about supporting, Gradle 6.6 supports kotlin 1.4, you just shouldn't use multiple kotlin versions at the same time. At the moment you have kotlin 1.3 in your `classpath` configuration (which your build uses) and Kotlin 1.5 in `compile` and `runtime` ones (which your app uses)

>Do you have a link for the gradle/kotlin incompatability?

I linked 2 issues in my original reply

**Comment by jeremymailen** [comment]
Well, not exactly. Both Kotlinter 3.4.0 and 3.4.3 depend on kotlin 1.4.x.
https://github.com/jeremymailen/kotlinter-gradle/blob/master/build.gradle.kts#L4

@mateuszkwiecinski linked two related issues above already ☝️ 

I can reproduce exactly your error when I downgrade my gradle wrapper to 6.6.

It can confirm it will work with either gradle 6.8 or 7.
I can also confirm it's working with both kotlin 1.4 and 1.5.

So the the upgrade you need to make is gradle to at least 6.8 and you should be good.

**Comment by LukevanTricht** [comment]
Aha! Thank you both. That explains a ton more. Apologies for wasting your time with this. Thank you for making kotlinter-gradle, we've had no issues till now 👍
