### ISSUE TITLE
Null Pointer Exception on upgrade to v3.14.0

### ISSUE THREAD

**Issue by LukevanTricht** [jeremymailen/kotlinter-gradle#323]
I'm getting a strange null pointer exception after upgrading to v3.14.0:

> Task :app:lintKotlinAndroidTest FAILED
lint worker execution error
java.lang.NullPointerException
        at com.pinterest.ktlint.core.internal.VisitorProvider.isRuleSetEnabled(VisitorProvider.kt:128)
        at com.pinterest.ktlint.core.internal.VisitorProvider.isRuleEnabled(VisitorProvider.kt:123)
        at com.pinterest.ktlint.core.internal.VisitorProvider.isEnabled(VisitorProvider.kt:102)
        at com.pinterest.ktlint.core.internal.VisitorProvider.visitor$ktlint_core(VisitorProvider.kt:55)
        at com.pinterest.ktlint.core.KtLintRuleEngine.lint(KtLint.kt:435)
        at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerAction.execute(LintWorkerAction.kt:48)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)

**Comment by hlandim** [comment]
I was getting the same error and stopping the gradle deamon `./gradlew --stop` fixed it for me.

**Comment by jeremymailen** [comment]
Yeah @LukevanTricht please try restarting the gradle daemon. It's been notorious for caching things it shouldn't between versions, so it might be an artifact of that.

**Comment by LukevanTricht** [comment]
Ahhh, Of course it was gradle 😅 That fixed it, thank you! Was pulling my hair out, didn't consider that Gradle wouldn't separate it's cache by version. Will keep that in mind for in future.
