### ISSUE TITLE
NoSuchFieldError: OPERATION_REFERENCE error on gradle 5.1.1

### ISSUE THREAD

**Issue by Coneys** [jeremymailen/kotlinter-gradle#94]
Hello, I upgraded Android Studio to 3.4, with gradle android plugin to 3.4 and gradle to 5.1.1 version. After that I cannot use kotliner anymore. 

Error:
Caused by: java.lang.NoSuchFieldError: OPERATION_REFERENCE
	at com.github.shyiko.ktlint.ruleset.standard.NoUnusedImportsRule$visit$1.invoke(NoUnusedImportsRule.kt:59)
	at com.github.shyiko.ktlint.ruleset.standard.NoUnusedImportsRule$visit$1.invoke(NoUnusedImportsRule.kt:13)
	at com.github.shyiko.ktlint.ruleset.standard.PackageKt.visit(package.kt:30)
	at com.github.shyiko.ktlint.ruleset.standard.NoUnusedImportsRule.visit(NoUnusedImportsRule.kt:52)
	at com.github.shyiko.ktlint.core.KtLint$format$1.invoke(KtLint.kt:339)
	at com.github.shyiko.ktlint.core.KtLint$format$1.invoke(KtLint.kt:36)
	at com.github.shyiko.ktlint.core.KtLint$visitor$2$2.invoke(KtLint.kt:207)
	at com.github.shyiko.ktlint.core.KtLint$visitor$2$2.invoke(KtLint.kt:36)
	at com.github.shyiko.ktlint.core.KtLint.visit(KtLint.kt:502)
	at com.github.shyiko.ktlint.core.KtLint.access$visit(KtLint.kt:36)
	at com.github.shyiko.ktlint.core.KtLint$visitor$2.invoke(KtLint.kt:206)
	at com.github.shyiko.ktlint.core.KtLint$visitor$2.invoke(KtLint.kt:36)
	at com.github.shyiko.ktlint.core.KtLint.format(KtLint.kt:334)
	at com.github.shyiko.ktlint.core.KtLint.format(KtLint.kt:285)
	at org.jmailen.gradle.kotlinter.tasks.FormatTask.formatKt(FormatTask.kt:72)
	at org.jmailen.gradle.kotlinter.tasks.FormatTask.access$formatKt(FormatTask.kt:15)
	at org.jmailen.gradle.kotlinter.tasks.FormatTask$run$1$1.invoke(FormatTask.kt:41)
	at org.jmailen.gradle.kotlinter.tasks.FormatTask$run$1$1.invoke(FormatTask.kt:15)

**Comment by jeremymailen** [comment]
Thank you for the report. Is your setup using kotlin 1.3.30?

I believe this is another manifestation of #93. ktlint needs an upgrade to kotlin 1.3.30 to be compatible since the kotlin team changed the types of some of these compiler symbols.

https://github.com/pinterest/ktlint/pull/376 is committed to fix the issue, but we're still waiting on a released version of ktlint with a published artifact we can pull into kotlinter-gradle.

**Comment by shashachu** [comment]
@jeremymailen Just released ktlint 0.32.0 which includes Kotlin 1.3.30 support. Let us know if you're still seeing issues.

**Comment by Coneys** [comment]
Cool, so if ktlint is now updated, now we have to wait for Kotlinter-gradle update, right?

**Comment by jeremymailen** [comment]
Yes, sorry for the delay -- I was out of the country. kotlinter-gradle 1.24.0 is out now and everything should be working.

**Comment by Coneys** [comment]
Everything works on 1.24 version, thanks!
